package comum;

public enum ComandoOperacao{
	
	CADASTRAR					,
	CONECTA						,
	CARREGAR_JOGO				,
	SOLICITAR_INICIAR_PARTIDA 	,
	INICIAR_PARTIDA				,
	SAIR_LISTA_ESPERA			,
	SAIR_PARTIDA				,
	ATUALIZA_CARTA_TERRITORIO	,
	ATUALIZA_TABULEIRO			,
	
	CONFIGURA_TABULEIRO		,
	EFETUAR_ATAQUE					,
	FINALIZA_JOGADA			,
	INICIA_JOGADA			,
	NOTIFICA_DESTRUICAO_EXERCITO ,
	
	
	RESPOSTA_CADASTRAR		,
	RESPOSTA_SAIR_LISTA_ESPERA ,
	RESPOSTA_SOLICITAR_INICIAR_PARTIDA ,
	RESPOSTA_SAIR_PARTIDA ,
	RESPOSTA_DEFESA ,
	RESPOSTA_FINALIZA_JOGADA ,
	RESPOSTA_ATUALIZA_CARTA_TERRITORIO ,
	RESPOSTA_CONEXAO ,
	
	BROADCAST_NOTIFICA_ATUALIZACAO_LISTA_JOGADORES		, 
	BROADCAST_NOTIFICA_SAIDA_LISTA_ESPERA 				,
	BROADCAST_CALLBACK_INICIO_PARTIDA 					,
	BROADCAST_NEGACAO_INICIO_PARTIDA					,
	BROADCAST_CONFIRMACAO_INICIO_PARTIDA				,
	BROADCAST_ATUALIZA_TABULEIRO						,
	BROADCAST_NOTIFICA_SAIDA_PARTIDA					,
	BROADCAST_NOTIFICA_ATAQUE							,
	BROADCAST_NOTIFICA_RESULTADO_ATAQUE					,
	BROADCAST_NOTIFICA_VENCEDOR

}
